In [116]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [117]:
df= pd.read_csv("ambulance_eta.csv")
df

,Unnamed: 0,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min,Region_Type,Road_Type,Emergency_Level
0,0,0.0,0,1,3.0,NaN,0.0,41.57,47.96,52.01,124.71,41.57,1.0,115.08,Suburban,Unpaved Road,Minor
1,1,1.0,0,1,2.0,0.0,2.0,34.72,56.41,36.93,69.44,0.00,1.0,49.04,Urban,Local Road,Major
2,2,1.0,0,1,1.0,0.0,0.0,11.91,30.67,23.30,11.91,0.00,0.0,16.74,Rural,Highway,Minor
3,3,1.0,0,1,2.0,1.0,0.0,10.15,50.58,12.04,20.30,10.15,1.0,26.50,Urban,Highway,Minor
4,4,2.0,0,1,1.0,0.0,1.0,28.47,51.76,33.00,28.47,0.00,0.0,38.83,Urban,Highway,Minor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100400,100400,19.0,1,0,2.0,0.0,2.0,22.21,44.34,30.05,44.42,0.00,1.0,43.57,Rural,Local Road,Minor
100401,100401,19.0,1,0,1.0,0.0,1.0,41.20,28.30,87.35,41.20,0.00,1.0,84.08,Suburban,Highway,Critical
100402,100402,20.0,0,0,1.0,0.0,1.0,27.64,49.97,33.19,27.64,0.00,1.0,51.37,Suburban,Unpaved Road,Minor
100403,100403,21.0,0,0,1.0,0.0,1.0,22.98,49.40,27.91,22.98,0.00,1.0,37.48,Urban,Highway,Minor
100404,100404,23.0,0,1,1.0,0.0,1.0,43.93,45.81,57.54,43.93,0.00,1.0,71.58,Suburban,Highway,Minor

In [118]:
df.shape

(100405, 17)

In [119]:
df = df.drop(df.columns[0],axis=1)

In [120]:
df.head()

,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min,Region_Type,Road_Type,Emergency_Level
0,0.0,0,1,3.0,NaN,0.0,41.57,47.96,52.01,124.71,41.57,1.0,115.08,Suburban,Unpaved Road,Minor
1,1.0,0,1,2.0,0.0,2.0,34.72,56.41,36.93,69.44,0.00,1.0,49.04,Urban,Local Road,Major
2,1.0,0,1,1.0,0.0,0.0,11.91,30.67,23.30,11.91,0.00,0.0,16.74,Rural,Highway,Minor
3,1.0,0,1,2.0,1.0,0.0,10.15,50.58,12.04,20.30,10.15,1.0,26.50,Urban,Highway,Minor
4,2.0,0,1,1.0,0.0,1.0,28.47,51.76,33.00,28.47,0.00,0.0,38.83,Urban,Highway,Minor

In [121]:
df.isna().sum()

Hour                     370
Is_Rush_Hour               0
Is_Night                   0
Traffic_Level           1226
Weather_Severity         990
Weather_Impact_Level     816
Distance_to_Incident    1046
Ambulance_Speed         1203
Base_Travel_Time_Min     623
Traffic_x_Distance       636
Weather_x_Distance       630
Is_Human_Dispatch        571
Ambulance_ETA_Min        556
Region_Type              743
Road_Type                922
Emergency_Level          621
dtype: int64

In [122]:
df.duplicated().sum()

np.int64(405)

In [123]:
df=df.drop_duplicates()

In [124]:
df.shape

(100000, 16)

In [125]:
df.info()

<class 'pandas.DataFrame'>
Index: 100000 entries, 0 to 100404
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Hour                  99630 non-null   float64
 1   Is_Rush_Hour          100000 non-null  int64
 2   Is_Night              100000 non-null  int64
 3   Traffic_Level         98777 non-null   float64
 4   Weather_Severity      99011 non-null   float64
 5   Weather_Impact_Level  99186 non-null   float64
 6   Distance_to_Incident  98956 non-null   float64
 7   Ambulance_Speed       98802 non-null   float64
 8   Base_Travel_Time_Min  99378 non-null   float64
 9   Traffic_x_Distance    99366 non-null   float64
 10  Weather_x_Distance    99373 non-null   float64
 11  Is_Human_Dispatch     99432 non-null   float64
 12  Ambulance_ETA_Min     99444 non-null   float64
 13  Region_Type           99261 non-null   str
 14  Road_Type             99083 non-null   str
 15  Emergency_Level       99381 non-null   str
dtypes: float64(11), int64(2), str(3)
memory usage: 14.8 MB

In [126]:
df.describe()

,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min
count,99630.000000,100000.000000,100000.000000,98777.000000,99011.000000,99186.000000,98956.000000,98802.000000,99378.000000,99366.000000,99373.000000,99432.000000,99444.000000
mean,11.566697,0.295890,0.331650,1.605252,0.247922,0.348991,26.516515,40.169124,43.551051,40.743550,6.351729,0.799199,52.680422
std,7.245649,0.461044,0.470808,0.696824,0.534208,0.569146,32.890169,10.559746,134.829558,29.904391,16.022208,0.400601,36.864356
min,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.000000,-1.000000,-3.000000,0.900000,0.000000,0.000000,-12.500000
25%,6.000000,0.000000,0.000000,1.000000,0.000000,0.000000,13.130000,34.190000,19.680000,17.990000,0.000000,1.000000,26.710000
50%,12.000000,0.000000,0.000000,1.000000,0.000000,0.000000,25.485000,39.830000,38.090000,34.545000,0.000000,1.000000,47.765000
75%,18.000000,1.000000,1.000000,2.000000,0.000000,1.000000,37.690000,45.660000,56.930000,54.120000,0.000000,1.000000,71.470000
max,99.000000,2.000000,1.000000,9.000000,2.000000,2.000000,999.990000,250.000000,5000.000000,169.050000,107.880000,1.000000,1174.690000

In [127]:
df.describe(include="object")

C:\Users\pushk\AppData\Local\Temp\ipykernel_16004\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

       Region_Type Road_Type Emergency_Level
count        99261     99083           99381
unique          14        14              13
top          Urban   Highway           Minor
freq         67740     57586           67687

# Data Overview

In [128]:
num_col = df.describe().columns
num_col

Index(['Hour', 'Is_Rush_Hour', 'Is_Night', 'Traffic_Level', 'Weather_Severity',
       'Weather_Impact_Level', 'Distance_to_Incident', 'Ambulance_Speed',
       'Base_Travel_Time_Min', 'Traffic_x_Distance', 'Weather_x_Distance',
       'Is_Human_Dispatch', 'Ambulance_ETA_Min'],
      dtype='str')

In [129]:
non_num_col = df.describe(include="object").columns
non_num_col

C:\Users\pushk\AppData\Local\Temp\ipykernel_16004\3325412589.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  non_num_col = df.describe(include="object").columns

Index(['Region_Type', 'Road_Type', 'Emergency_Level'], dtype='str')

In [130]:
df["Region_Type"].value_counts()

Region_Type
Urban         67740
Suburban      19204
Rural          9606
 Urban          579
urban           573
URBAN           571
Unknown         252
 Suburban       161
SUBURBAN        156
suburban        146
rural            88
RURAL            75
 Rural           70
Sub-urban        40
Name: count, dtype: int64

In [131]:
df["Road_Type"].value_counts()

Road_Type
Highway           57586
Local Road        29034
Unpaved Road       9596
 Highway            511
HIGHWAY             492
highway             489
Unknown             312
LOCAL ROAD          258
local road          243
 Local Road         239
UNPAVED ROAD        100
 Unpaved Road        93
unpaved road         82
Local Rd             48
Name: count, dtype: int64

In [132]:
df["Emergency_Level"].value_counts()

Emergency_Level
Minor         67687
Major         19295
Critical       9731
MINOR           627
minor           565
 Minor          550
Unknown         200
 Major          170
MAJOR           161
major           157
critical         86
CRITICAL         78
 Critical        74
Name: count, dtype: int64

In [133]:
df["Weather_Severity"].value_counts()

Weather_Severity
0.0    79361
1.0    14753
2.0     4897
Name: count, dtype: int64

In [134]:
df["Weather_Impact_Level"].value_counts()

Weather_Impact_Level
0.0    69368
1.0    25021
2.0     4797
Name: count, dtype: int64

In [135]:
df["Is_Human_Dispatch"].value_counts()

Is_Human_Dispatch
1.0    79466
0.0    19966
Name: count, dtype: int64

In [136]:
df["Distance_to_Incident"].min()

np.float64(-5.0)

In [137]:
df["Ambulance_ETA_Min"].min()

np.float64(-12.5)

In [138]:
df["Ambulance_ETA_Min"].max()

np.float64(1174.69)

In [139]:
col_to_check  = ["Distance_to_Incident", "Ambulance_Speed", "Base_Travel_Time_Min","Traffic_x_Distance", "Weather_x_Distance", "Ambulance_ETA_Min"]

# Data Cleaning

In [140]:
for c in non_num_col:
    df[c] = df[c].str.strip().str.title()

In [141]:
df[non_num_col]

       Region_Type     Road_Type Emergency_Level
0         Suburban  Unpaved Road           Minor
1            Urban    Local Road           Major
2            Rural       Highway           Minor
3            Urban       Highway           Minor
4            Urban       Highway           Minor
...            ...           ...             ...
100400       Rural    Local Road           Minor
100401    Suburban       Highway        Critical
100402    Suburban  Unpaved Road           Minor
100403       Urban       Highway           Minor
100404    Suburban       Highway           Minor

[100000 rows x 3 columns]

In [142]:
df[non_num_col].nunique()

Region_Type        5
Road_Type          5
Emergency_Level    4
dtype: int64

In [143]:
df["Region_Type"].value_counts()

Region_Type
Urban        69463
Suburban     19667
Rural         9839
Unknown        252
Sub-Urban       40
Name: count, dtype: int64

In [144]:
df["Road_Type"].value_counts()

Road_Type
Highway         59078
Local Road      29774
Unpaved Road     9871
Unknown           312
Local Rd           48
Name: count, dtype: int64

In [145]:
df["Emergency_Level"].value_counts()

Emergency_Level
Minor       69429
Major       19783
Critical     9969
Unknown       200
Name: count, dtype: int64

In [146]:
df["Road_Type"] = df["Road_Type"].replace({"Local Rd": "Local Road"})
df["Region_Type"] = df["Region_Type"].replace({"Sub-Urban": "Suburban"})

In [147]:
df = df.replace(["", "Unknown", "N/A", "NA", "null", "?"], np.nan)

In [148]:
df.isna().sum()

Hour                     370
Is_Rush_Hour               0
Is_Night                   0
Traffic_Level           1223
Weather_Severity         989
Weather_Impact_Level     814
Distance_to_Incident    1044
Ambulance_Speed         1198
Base_Travel_Time_Min     622
Traffic_x_Distance       634
Weather_x_Distance       627
Is_Human_Dispatch        568
Ambulance_ETA_Min        556
Region_Type              991
Road_Type               1229
Emergency_Level          819
dtype: int64

In [149]:
for c in non_num_col:
    print(df[c].value_counts(dropna=False), "\n")

Region_Type
Urban       69463
Suburban    19707
Rural        9839
NaN           991
Name: count, dtype: int64

Road_Type
Highway         59078
Local Road      29822
Unpaved Road     9871
NaN              1229
Name: count, dtype: int64

Emergency_Level
Minor       69429
Major       19783
Critical     9969
NaN           819
Name: count, dtype: int64

In [150]:
df.loc[(df["Distance_to_Incident"] <= 0) | (df["Distance_to_Incident"] > 80), "Distance_to_Incident"] = np.nan

In [151]:
df.loc[(df["Ambulance_Speed"] <= 0) | (df["Ambulance_Speed"] > 100), "Ambulance_Speed"] = np.nan

In [152]:
df.loc[~df["Hour"].between(0, 23), "Hour"] = np.nan

In [153]:
df.loc[~df["Traffic_Level"].isin([1, 2, 3]), "Traffic_Level"] = np.nan

In [154]:
df.loc[~df["Is_Rush_Hour"].isin([0, 1]), "Is_Rush_Hour"] = np.nan

In [155]:
df.loc[(df["Base_Travel_Time_Min"] <= 0) | (df["Base_Travel_Time_Min"] > 300), "Base_Travel_Time_Min"] = np.nan

In [156]:
df.loc[(df["Ambulance_ETA_Min"] <= 0) | (df["Ambulance_ETA_Min"] > 180), "Ambulance_ETA_Min"] = np.nan

In [157]:
df.isna().sum()

Hour                     562
Is_Rush_Hour             211
Is_Night                   0
Traffic_Level           1417
Weather_Severity         989
Weather_Impact_Level     814
Distance_to_Incident    1365
Ambulance_Speed         1443
Base_Travel_Time_Min     829
Traffic_x_Distance       634
Weather_x_Distance       627
Is_Human_Dispatch        568
Ambulance_ETA_Min        868
Region_Type              991
Road_Type               1229
Emergency_Level          819
dtype: int64

In [159]:
df.loc[df["Ambulance_ETA_Min"].isna()]

,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min,Region_Type,Road_Type,Emergency_Level
27,14.0,0.0,0,1.0,0.0,0.0,45.46,36.02,75.72,45.46,0.00,0.0,NaN,Urban,Highway,Minor
30,16.0,1.0,0,1.0,0.0,1.0,32.36,25.11,77.32,32.36,0.00,1.0,NaN,Urban,Highway,Major
43,23.0,0.0,1,1.0,2.0,1.0,34.72,39.48,52.77,34.72,69.44,1.0,NaN,Suburban,Highway,NaN
278,20.0,0.0,0,1.0,0.0,0.0,13.62,41.99,19.46,13.62,0.00,0.0,NaN,Urban,Highway,Major
447,10.0,0.0,0,1.0,0.0,1.0,29.56,53.78,32.98,29.56,0.00,1.0,NaN,Urban,Highway,Minor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100071,8.0,1.0,0,1.0,0.0,0.0,10.84,48.97,13.28,10.84,0.00,0.0,NaN,Urban,Unpaved Road,Minor
100145,12.0,0.0,0,1.0,0.0,1.0,39.45,24.01,98.58,39.45,0.00,1.0,NaN,Suburban,Highway,Minor
100177,10.0,0.0,0,1.0,0.0,0.0,40.68,19.95,122.35,40.68,0.00,1.0,NaN,Suburban,Highway,Critical
100196,23.0,0.0,1,2.0,0.0,0.0,38.05,35.86,63.66,76.10,0.00,1.0,NaN,Suburban,Local Road,Major
100296,5.0,0.0,1,1.0,0.0,0.0,30.76,39.42,46.82,30.76,0.00,1.0,NaN,Urban,Local Road,Minor

In [162]:
df.loc[df["Distance_to_Incident"].isna()]

,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min,Region_Type,Road_Type,Emergency_Level
80,21.0,0.0,0,2.0,0.0,0.0,NaN,47.01,20.10,31.50,0.0,1.0,37.34,Suburban,Local Road,Major
219,7.0,1.0,0,1.0,0.0,0.0,NaN,26.67,31.38,13.95,0.0,1.0,34.03,Urban,Highway,Major
243,16.0,1.0,0,1.0,0.0,0.0,NaN,45.88,12.24,9.36,0.0,1.0,15.42,Urban,Highway,Minor
325,6.0,0.0,0,1.0,0.0,0.0,NaN,51.47,12.87,11.04,0.0,1.0,19.20,Urban,Local Road,Minor
361,6.0,0.0,0,1.0,NaN,0.0,NaN,45.02,46.03,34.54,0.0,1.0,45.34,Urban,Local Road,Minor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100125,2.0,0.0,1,1.0,0.0,0.0,NaN,36.91,41.19,25.34,0.0,1.0,47.82,Urban,Highway,Minor
100175,4.0,0.0,1,1.0,0.0,0.0,NaN,33.53,41.00,22.91,0.0,0.0,37.11,Urban,Highway,Minor
100285,21.0,0.0,0,2.0,1.0,0.0,NaN,46.05,20.98,32.20,16.1,1.0,32.27,Urban,Local Road,Minor
100330,1.0,0.0,1,2.0,0.0,1.0,NaN,46.97,31.81,49.80,0.0,1.0,39.51,Urban,Highway,Major
100335,5.0,0.0,1,1.0,0.0,1.0,NaN,31.94,14.82,7.89,0.0,1.0,22.60,Urban,Highway,Minor

In [163]:
df  =df.dropna()
df.isna().sum()

Hour                    0
Is_Rush_Hour            0
Is_Night                0
Traffic_Level           0
Weather_Severity        0
Weather_Impact_Level    0
Distance_to_Incident    0
Ambulance_Speed         0
Base_Travel_Time_Min    0
Traffic_x_Distance      0
Weather_x_Distance      0
Is_Human_Dispatch       0
Ambulance_ETA_Min       0
Region_Type             0
Road_Type               0
Emergency_Level         0
dtype: int64

In [164]:
df.info()

<class 'pandas.DataFrame'>
Index: 87425 entries, 1 to 100404
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Hour                  87425 non-null  float64
 1   Is_Rush_Hour          87425 non-null  float64
 2   Is_Night              87425 non-null  int64
 3   Traffic_Level         87425 non-null  float64
 4   Weather_Severity      87425 non-null  float64
 5   Weather_Impact_Level  87425 non-null  float64
 6   Distance_to_Incident  87425 non-null  float64
 7   Ambulance_Speed       87425 non-null  float64
 8   Base_Travel_Time_Min  87425 non-null  float64
 9   Traffic_x_Distance    87425 non-null  float64
 10  Weather_x_Distance    87425 non-null  float64
 11  Is_Human_Dispatch     87425 non-null  float64
 12  Ambulance_ETA_Min     87425 non-null  float64
 13  Region_Type           87425 non-null  str
 14  Road_Type             87425 non-null  str
 15  Emergency_Level       87425 non-null  str
dtypes: float64(12), int64(1), str(3)
memory usage: 13.0 MB

In [165]:
df.describe()

,Hour,Is_Rush_Hour,Is_Night,Traffic_Level,Weather_Severity,Weather_Impact_Level,Distance_to_Incident,Ambulance_Speed,Base_Travel_Time_Min,Traffic_x_Distance,Weather_x_Distance,Is_Human_Dispatch,Ambulance_ETA_Min
count,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000,87425.000000
mean,11.526074,0.292262,0.330947,1.599131,0.247938,0.349454,25.467196,40.014035,40.033167,40.723663,6.336461,0.799257,52.014220
std,6.912467,0.454805,0.470557,0.664450,0.533959,0.569365,14.203848,8.509029,24.765738,29.882096,15.991615,0.400559,31.864912
min,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.900000,0.500000,0.960000,0.900000,0.000000,0.000000,2.000000
25%,6.000000,0.000000,0.000000,1.000000,0.000000,0.000000,13.130000,34.210000,19.710000,17.940000,0.000000,1.000000,26.740000
50%,12.000000,0.000000,0.000000,1.000000,0.000000,0.000000,25.450000,39.840000,38.040000,34.600000,0.000000,1.000000,47.690000
75%,18.000000,1.000000,1.000000,2.000000,0.000000,1.000000,37.660000,45.640000,56.890000,54.120000,0.000000,1.000000,71.320000
max,23.000000,1.000000,1.000000,3.000000,2.000000,2.000000,58.300000,80.150000,186.070000,169.050000,107.560000,1.000000,175.560000